FROM python:3

RUN apt-get update && \
    apt-get install -y ca-certificates libyaml-dev && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]
